/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.panes;

import java.awt.BorderLayout;
import restaurante.rules.Permissoes;
import restaurante.personalizacao.Personalizacoes;
import restaurante.personalizacao.CriarSubJanela;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class ManagerPanel extends javax.swing.JPanel {
    Color secondaryColor = new Color(255, 243, 224); // Creme claro
    private final List<Permissoes> permissoes;
    private final String nomeUsuario;

    public ManagerPanel(List<Permissoes> permissoes, String nomeUsuario) {
        initComponents();
        this.permissoes = permissoes;
        this.nomeUsuario = nomeUsuario;
        CarregarUsuario();
        configurarPermissoes();
        personalizarInterface();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioButton = new javax.swing.JButton();
        userConfigButton = new javax.swing.JButton();

        usuarioButton.setText("Usuario");
        usuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioButtonActionPerformed(evt);
            }
        });

        userConfigButton.setText("Usuários");
        userConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userConfigButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(usuarioButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(userConfigButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuarioButton)
                .addGap(65, 65, 65)
                .addComponent(userConfigButton)
                .addContainerGap(259, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioButtonActionPerformed
        CriarSubJanela.subMenuLougout(usuarioButton, (JFrame) this.getTopLevelAncestor());
    }//GEN-LAST:event_usuarioButtonActionPerformed

    private void userConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userConfigButtonActionPerformed
        // Exibe o painel StartPanel de acordo com as permissões
            var managerPanel = new UserPanel(this.permissoes, this.nomeUsuario);
            JFrame startFrame = new JFrame("Configurações de usuários");
            startFrame.setSize(400, 300);
            startFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            startFrame.setLocationRelativeTo(null);
            startFrame.add(managerPanel);
            startFrame.setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximiza o JFrame
            startFrame.setUndecorated(true);

            // Cria uma barra de título personalizada
            JPanel titleBar = Personalizacoes.criarBarraDeTituloPadrao(startFrame);

            // Usa um JRootPane para simular uma barra de título customizada
            JRootPane rootPane = startFrame.getRootPane();
            rootPane.setWindowDecorationStyle(JRootPane.NONE); // Remove a decoração padrão

            // Cria um painel principal e adiciona a barra de título customizada
            JPanel contentPane = new JPanel(new BorderLayout());
            contentPane.add(titleBar, BorderLayout.NORTH);
            contentPane.add(new UserPanel(this.permissoes, this.nomeUsuario), BorderLayout.CENTER);
            startFrame.setContentPane(contentPane);

            // Altera o ícone da janela (coloque o ícone na pasta resources ou no mesmo diretório)
            startFrame.setIconImage(new ImageIcon("/images/icon.png").getImage());

            startFrame.setVisible(true);
            JFrame loginFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            loginFrame.dispose();
    }//GEN-LAST:event_userConfigButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton userConfigButton;
    private javax.swing.JButton usuarioButton;
    // End of variables declaration//GEN-END:variables

    private void CarregarUsuario() {
        String seta = "↓";
        usuarioButton.setText(nomeUsuario + seta);

    }

    private void configurarPermissoes() {
        userConfigButton.setVisible(false);
        if (permissoes.contains(Permissoes.MASTER) || permissoes.contains(Permissoes.ADMINISTRADOR)){
            userConfigButton.setVisible(true);
        }
    }

    private void personalizarInterface() {
        // Personaliza os labels
        Personalizacoes.personalizarBotao(usuarioButton, 16, false,null,null);
        Personalizacoes.personalizarBotao(userConfigButton, 16, true,null,null);

        // Fundo do painel
        setBackground(secondaryColor);
    }
}
